### PR TITLE
Add surfacing mode in path planning widget and service

### PR DESCRIPTION
**Pull request by KevinBollore**
Fixes differents points in #18 

- Add an option to enable/disable surfacing mode
- Use the surfacing mode of Bezier

Ready for review.
@VictorLamoine, does this UI is OK for you?
CheckBox for surfacing mode checked:
capture du 2016-06-16 18 27 37

CheckBox for surfacing mode unchecked:
capture du 2016-06-16 18 27 16

### CODE REVIEW

**Comment by VictorLamoine** [comment]
I would rather put the check box on the right.of.the label.

We still need to provide a lean angle when in surfacing mode so you are disabling too much of the UI

**Comment by KevinBollore** [comment]
My mistake. I thought about it but totally forgot after.
What about this?
capture du 2016-06-17 08 55 27

**Comment by VictorLamoine** [comment]
I think covering percentage is used too; make a list of what parameters are useful when using the surfacing mode and make sure they stay enabled.

**Comment by KevinBollore** [comment]
At least, when we are in surfacing mode, Bezier just ignore `maximum_depth_of_path` parameter, so:

capture du 2016-06-17 09 33 30

**Comment by VictorLamoine** [comment]
See https://github.com/KevinBollore/fanuc_grinding/pull/1

**Comment by VictorLamoine** [comment]
See #44

**Pull request closed without merging**
