### PR TITLE
Path planning improvements

### PR DESCRIPTION
**Pull request by VictorLamoine**
Nothing very functional, mostly GUI simplification/cleaning.

- The angle is entered in degrees and converted/sent as radians.
- The grinder diameter and depth of pass are entered in millimeters and converted/sent as meters.

This is part of issue #18

### CODE REVIEW

**Comment by VictorLamoine** [comment]
@KevinBollore please review!

**Comment by KevinBollore** [comment]
Apparently, there is problem with your signals in your connects.
My terminal:
```
Object::connect: No such signal QDoubleSpinBox::valueChanged(int)
Object::connect:  (receiver name: 'PathPlanningWidget_')
Object::connect: No such signal QDoubleSpinBox::valueChanged(int)
Object::connect:  (receiver name: 'PathPlanningWidget_')
```

**Comment by KevinBollore** [comment]
It is a screen shot from my test. Does the GUI for path planning should be like this?

capture du 2016-06-13 13 50 31

**Comment by VictorLamoine** [comment]
Yes, you don't like it?

**Comment by KevinBollore** [comment]
Ok for the connect.
I prefer the second one, the first one disturb me with all this space between the parameters and the buttons. But it doesn't matter, it is only style. As you want.

**Comment by VictorLamoine** [comment]
Let's go for the second option, thanks for the review!

**Pull request merged**
